# -*- coding: utf-8 -*-
"""project part1,2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRJ_U2M9R4Ek21NRDWCFhwVtZFgs_dSt
"""

import matplotlib.pyplot as plt
import numpy as np

# Data (reusing the lists from the previous cell)
assignment_1 = ['y','y','n','n','n','y','n','n','n','n','y','y','n','n','n','n','n','n','y','n','n','n','y','n','n','n','n','n','y','y','n','n','y','n','n','n','y','y','n','n','n','y','n','n','y','n','n','n','n','n','n','y','y','n','n','y','y','n','y','n','y','y','y']
assignment_2 = ['y','y','y','n','n','y','y','y','y','y','y','n','n','n','y','y','n','y','y','n','y','y','y','n','n','y','n','y','y','y','y','y','y','y','y','n','y','y','y','n','y','y','y','y','y','y','n','y','y','n','n','y','y','y','n','y','y','y','y','y','y','y','y']
assignment_3 = ['n','y','n','n','n','n','y','n','n','y','n','n','n','n','n','n','n','y','y','n','y','y','n','n','y','y','y','n','y','y','y','y','n','y','n','y','y','n','y','n','n','n','n','y','n','y','n','y','n','n','n','y','n','n','n','n','n','n','y','n','y','n','y']

assignments = [assignment_1, assignment_2, assignment_3]
assignment_labels = ["Assignment 1", "Assignment 2", "Assignment 3"]

# Calculate counts of 'y' and 'n' for each assignment
y_counts = [assignment.count('y') for assignment in assignments]
n_counts = [assignment.count('n') for assignment in assignments]

# Create side-by-side bar charts
fig, ax = plt.subplots(figsize=(8, 5))

bar_width = 0.35
indices = np.arange(len(assignments))

bar_y = ax.bar(indices - bar_width/2, y_counts, bar_width, label='y')
bar_n = ax.bar(indices + bar_width/2, n_counts, bar_width, label='n')

ax.set_xlabel("Assignments")
ax.set_ylabel("Count")
ax.set_title("Counts of 'y' and 'n' for Each Assignment")
ax.set_xticks(indices)
ax.set_xticklabels(assignment_labels)
ax.legend()

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Students S1 to S63
students = [f"S{i}" for i in range(1, 64)]

# Internal marks with 'ab' for absent
test1 = [9,10.5,27,22,1,2,15,15,8.5,22,'ab',9,0,0,10,8,10.5,20.5,7.5,16,23,3,3,'ab',27,24,24,19,12.5,14,19,18,10.5,0,5,'ab',12.5,6,28,14,16.5,13.5,11,12,24.5,25,1,21.5,0,7,15,0,2,0,1,10,4,14,9,0,13,9,6]
test2 = [16,20.5,25.5,'ab',14,12,12,9,15,'ab',8,7,'ab',6,14,8.5,13.5,28,22,3,25,8,12,'ab','ab',9,12,22,18,27,23,17,15,13,16,12,24,13.5,28,12,'ab',16,17,20.5,16,19.5,3,23,13,7.5,12,12,7,0,6,24,9,14,19,0,20,7,13]

# Replace 'ab' with np.nan
test1_numeric = [np.nan if x == 'ab' else x for x in test1]
test2_numeric = [np.nan if x == 'ab' else x for x in test2]

x = np.arange(len(students))  # positions
width = 0.45  # slightly bigger bars

plt.figure(figsize=(18,6))

# Plot bars
plt.bar(x - width/2, test1_numeric, width, color='darkblue', label='Test 1', edgecolor='black')
plt.bar(x + width/2, test2_numeric, width, color='lightblue', label='Test 2', edgecolor='black')

for i, val in enumerate(test1):
   if val == 'ab':
        plt.plot(x[i] - width/2, 0, '|', color='red', markersize=27, label='Absent (Test 1)' if 'Absent (Test 1)' not in plt.gca().get_legend_handles_labels()[1] else "")

for i, val in enumerate(test2):
    if val == 'ab':
        plt.plot(x[i] + width/2, 0, '|', color='red', markersize=27, label='Absent (Test 2)' if 'Absent (Test 2)' not in plt.gca().get_legend_handles_labels()[1] else "")

# Titles and labels
plt.title("Internal Marks for 63 Students", fontsize=18, weight='bold')
plt.xlabel("Students", fontsize=14)
plt.ylabel("Marks", fontsize=14)

# X-axis labels
plt.xticks(x, students, rotation=90)

# Grid for clarity
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Legend
plt.legend(fontsize=12)

# Tight layout for neatness
plt.tight_layout()
plt.show()